# Nama workflow
name: Publish Docker Image to GitHub Packages

# Pemicu workflow
on:
  push:
    branches: ["main"] # Berjalan setiap push ke branch main
  # pull_request:
  #   branches: [ "main" ]

# Pekerjaan yang akan dieksekusi
jobs:
  push_to_registry:
    name: Build and Push Docker Image
    # Sistem operasi yang digunakan
    runs-on: ubuntu-latest

    # Izin yang diperlukan untuk push ke GitHub Container Registry (ghcr.io)
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout kode dari repository
      - name: Check out the repo
        uses: actions/checkout@v4

      # 2. Login ke GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Ekstrak metadata (tag dan label) untuk Docker image
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # 4. Build dan push Docker image ke registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
